### ISSUE TITLE
Chart overlaps with text 

### ISSUE THREAD

**Issue by vogella** [mickaelistria/eclipse-ide-parallel-builds-demo#2]
![selection_696](https://user-images.githubusercontent.com/139910/46631826-d8316600-cb48-11e8-9cc8-e7439e602593.png)

See screenshot, the chart overlaps with the text.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/mickaelistria/eclipse-ide-parallel-builds-demo/commit/78a4e85a6de7424c9ca789bf2247fcf96c7b5207
